### ISSUE TITLE
Dependencies: Run build in post install hook

### ISSUE THREAD

**Issue by mejiaj** [Bixal/bixaluswds#2]
[Starter theme](https://github.com/Bixal/bixaluswds/tree/dev/starter_theme) has instructions to run NPM commands

```bash
nvm use
npm install
npm run build
```

Adding a postinstall hook to `package.json` would save us a step.

https://github.com/Bixal/bixaluswds/blob/6bf76921d5c7b5b0a7cc500d606cdef20cf363bf/starter_theme/package.json#L6-L9

Calling `npm run build` here will always run it after install.

## Tasks

- [x] Create `postinstall` script
- [x] Update `starter_theme` README

**Comment by rayestrada** [comment]
This issue is complete.
