### ISSUE TITLE
CSS is stale after a change when it is being aggregated

### ISSUE THREAD

**Issue by mattsqd** [Bixal/bixaluswds#21]
https://www.drupal.org/project/drupal/issues/3370828

You can tell it will never update because no matter how much you clear cache, Drupal will rebuild the aggregated CSS with the same URL.

**Comment by rayestrada** [comment]
Update starter_theme.libraries.yml to remove `version` properties unless maintained by project team.

**Comment by rayestrada** [comment]
Resolved in [cea8e71](https://github.com/Bixal/bixaluswds/commit/cea8e71ff96738d55a72fa151fcb42fe5269fc3d)
