### ISSUE TITLE
Add editorconfig file to standardize code style

### ISSUE THREAD

**Issue by mejiaj** [Bixal/bixaluswds#3]
Add an [editorconfig](https://editorconfig.org/) file to follow spacing conventions for code. Follow [Drupal coding standards](https://www.drupal.org/docs/develop/standards)

**Comment by cathybaptista** [comment]
Hi, James

I can work on this. :)

**Comment by cathybaptista** [comment]
I committed the .editorconfig and submitted a pull request. The keys I included were the ones that seemed the most relevent right now, but we can add to it whatever we need to. :)
