### ISSUE TITLE
Add default image styles to base theme

### ISSUE THREAD

**Issue by lacorie-bixal** [Bixal/bixaluswds#5]
Work with other Front End Developers to determine a "standard" for image styles and add them to the bases theme in a install directory

**Comment by CTGM-Bixal** [comment]
I'd like to help with this!

**Comment by rayestrada** [comment]
**List of Tasks**
1. Add required modules: Focal Point, Responsive images, Breakpoint #10 
2. Breakpoints added for mobile, tablet, desktop using USWDS widths #10 
4. Add install config for "Scaled": 3 size variants based on width 640, 960, 1280 #10 
5. Add install config for "Square (1:1)": 3 size variants based on crop 640x640, 960x960, 1280x1280 using focal point scale and crop
6. Add install config for "Standard (4:3)": 3 size variants based on crop 640x480, 960x720, 1280x960 using focal point scale and crop
7. Add install config for "Wide Standard (16:9)": 3 size variants based on crop 640x360, 960x540, 1280x720 using focal point scale and crop
8.Add install config for "Banner (2:1)": 3 size variants based on crop 960x480, 1280x640, 1600x800 using focal point scale and crop 
9. Add install config for "Social standard": 1 size variants based on crop 1200x600 using focal point scale and crop
10. Add install config for a responsive image style using "Scaled" and breakpoints #10 
11. Add install config for a responsive image style using "Square" and breakpoints
12. Add install config for a responsive image style using "Standard" and breakpoints
13. Add install config for a responsive image style using "Wide Standard" and breakpoints
14. Add install config for a responsive image style using "Banner" and breakpoints

**Comment by rayestrada** [comment]
I've created an PR to start this work #10 . For the additional image styles I expect them to follow the same pattern.

**Comment by CTGM-Bixal** [comment]
Issue Complete!

...
List of Tasks

1. Add required modules: Focal Point, Responsive images, Breakpoint #10 
2. Breakpoints added for mobile, tablet, desktop using USWDS widths #10 
3. Add install config for "Scaled": 3 size variants based on width 640, 960, 1280 #10 
4. Add install config for "Square (1:1)": 3 size variants based on crop 640x640, 960x960, 1280x1280 using focal point scale and crop #13 
5. Add install config for "Standard (4:3)": 3 size variants based on crop 640x480, 960x720, 1280x960 using focal point scale and crop #13 
6. Add install config for "Wide Standard (16:9)": 3 size variants based on crop 640x360, 960x540, 1280x720 using focal point scale and crop #13 
7. Add install config for "Banner (2:1)": 3 size variants based on crop 960x480, 1280x640, 1600x800 using focal point scale and crop #13 
8. Add install config for "Social standard": 1 size variants based on crop 1200x600 using focal point scale and crop #13 
9. Add install config for a responsive image style using "Scaled" and breakpoints https://github.com/Bixal/bixaluswds/issues/10
10. Add install config for a responsive image style using "Square" and breakpoints #13 
11. Add install config for a responsive image style using "Standard" and breakpoints #13 
12. Add install config for a responsive image style using "Wide Standard" and breakpoints #13 
13. Add install config for a responsive image style using "Banner" and breakpoints #13

**Comment by rayestrada** [comment]
Changed were merged into `dev`. This is complete.
