### ISSUE TITLE
Documentation: Create contribution guidelines

### ISSUE THREAD

**Issue by mejiaj** [Bixal/bixaluswds#6]
Create `CONTRIBUTING.md`. 

GitHub guidance for ideas & examples - [Setting guidelines for repository contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#about-contributing-guidelines)

**Example**
https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

**Comment by rayestrada** [comment]
This file is initialized in the repo. Additional work can be tracked separately.
